---
# cPanel Deployment Configuration for Go-pay React/Vite Application
# This file builds the app and deploys to public_html

deployment:
  tasks:
    # Set deployment path to public_html directory
    - export DEPLOYPATH=/home/$USER/public_html/
    
    # Install dependencies and build the application
    - npm install
    - npm run build
    
    # Clean previous deployment (removes old files)
    - rm -rf $DEPLOYPATH*
    
    # Deploy all files from dist directory
    - /bin/cp -R dist/* $DEPLOYPATH
    
    # Set proper permissions for files and directories
    - chmod -R 755 $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
